export const DEFAULT_PRODUCT_SEEDS = [
  {
    name: '에그타르트',
    aliases: ['에그타르트', '에그 타르트', 'egg tart'],
    category: 'bakery',
    group: 'tart',
    countInBakeryTotal: true,
  },
  {
    name: '레몬 케이크',
    aliases: ['레몬 케이크', '레몬케이크', '레몬 케익'],
    category: 'bakery',
    group: 'cake',
    countInBakeryTotal: true,
  },
  {
    name: '휘낭시에',
    aliases: [
      '휘낭시에',
      '휘낭시예',
      '휘낭시애',
      '휭낭시에',
      '휭낭시예',
      '휘낭시에 플레인',
      '휘낭시에 무화과',
    ],
    category: 'bakery',
    group: 'pastry',
    countInBakeryTotal: true,
  },
  {
    name: '마늘빵',
    aliases: ['마늘빵'],
    category: 'bakery',
    group: 'bread',
    countInBakeryTotal: true,
  },
  {
    name: '소금빵',
    aliases: ['소금빵'],
    category: 'bakery',
    group: 'bread',
    countInBakeryTotal: true,
  },
  {
    name: '카야버터 소금빵',
    aliases: ['카야버터 소금빵', '카야버터소금빵'],
    category: 'bakery',
    group: 'bread',
    countInBakeryTotal: true,
  },
  {
    name: '블루베리 식빵',
    aliases: ['블루베리 식빵', '블루베리식빵'],
    category: 'bakery',
    group: 'bread',
    countInBakeryTotal: true,
  },
  {
    name: '베이커리 츄러스',
    aliases: ['베이커리 츄러스', '베이커리츄러스', '츄러스'],
    category: 'bakery',
    group: 'dessert',
    countInBakeryTotal: true,
  },
  {
    name: '앙버터',
    aliases: ['앙버터'],
    category: 'bakery',
    group: 'bread',
    countInBakeryTotal: true,
  },
  {
    name: '잠봉뵈르 샌드위치',
    aliases: ['잠봉뵈르 샌드위치', '잠봉뵈르', '잠봉뵈르샌드위치'],
    category: 'food',
    group: 'sandwich',
    countInBakeryTotal: false,
  },
  {
    name: '아보카도 샌드위치',
    aliases: ['아보카도 샌드위치', '아보카도샌드위치'],
    category: 'food',
    group: 'sandwich',
    countInBakeryTotal: false,
  },
  {
    name: '아메리카노',
    aliases: ['아메리카노', '아이스아메리카노', 'ice americano'],
    category: 'drink',
    group: 'coffee',
    countInBakeryTotal: false,
  },
  {
    name: '라떼',
    aliases: ['라떼', '카페라떼', 'latte'],
    category: 'drink',
    group: 'coffee',
    countInBakeryTotal: false,
  },
  {
    name: '비건라떼',
    aliases: ['비건라떼', '비건 라떼', '귀리로 만든 라떼'],
    category: 'drink',
    group: 'coffee',
    countInBakeryTotal: false,
  },
  {
    name: '마다가스카르 바닐라빈 라떼',
    aliases: [
      '마다가스카르 바닐라빈 라떼',
      '마다가스카르바닐라빈라떼',
      '바닐라빈 라떼',
    ],
    category: 'drink',
    group: 'coffee',
    countInBakeryTotal: false,
  },
  {
    name: '콜드브루 원액 1L',
    aliases: ['콜드브루 원액 1L', '콜드브루원액1L', '콜드브루 원액'],
    category: 'drink',
    group: 'bean',
    countInBakeryTotal: false,
  },
  {
    name: '커피원두 (오랑 400g)',
    aliases: ['커피원두', '커피원두 오랑 400g', '오랑 400g'],
    category: 'goods',
    group: 'bean',
    countInBakeryTotal: false,
  },
  {
    name: '이즈드립',
    aliases: ['이즈드립'],
    category: 'drink',
    group: 'coffee',
    countInBakeryTotal: false,
  },
  {
    name: '구리볼',
    aliases: ['구리볼'],
    category: 'unknown',
    group: 'unknown',
    countInBakeryTotal: false,
  },
]
