export const DEFAULT_PRODUCT_SEEDS = [
  {
    name: '에그타르트',
    aliases: ['에그타르트', '에그타르트', '에그타르트'],
    category: '빵집',
    group: '타르트',
    countInBakeryTotal: true,
  },
  {
    name: '레몬케이크',
    aliases: ['레몬케이크', '레몬케이크', '레몬케익'],
    category: '빵집',
    group: '케이크',
    countInBakeryTotal: true,
  },
  {
    name: '휘낭시에',
    aliases: [
      '휘낭시에',
      '휘낭시예',
      '휘낭시에 플레인',
      '휘낭시에 무화과',
      '휘낭시애',
    ],
    category: '빵집',
    group: '페이스트리',
    countInBakeryTotal: true,
  },
  {
    name: '마늘빵',
    aliases: ['마늘빵'],
    category: '빵집',
    group: '빵',
    countInBakeryTotal: true,
  },
  {
    name: '소금빵',
    aliases: ['소금빵'],
    category: '빵집',
    group: '빵',
    countInBakeryTotal: true,
  },
  {
    name: '카야버터 소금빵',
    aliases: ['카야버터 소금빵', '카야버터소금빵'],
    category: '빵집',
    group: '빵',
    countInBakeryTotal: true,
  },
  {
    name: '블루베리 식빵',
    aliases: ['블루베리 식빵', '블루베리 식빵'],
    category: '빵집',
    group: '빵',
    countInBakeryTotal: true,
  },
  {
    name: '베이커리 츄러스',
    aliases: ['베이커리 츄러스', '베이커리츄러스', '츄러스'],
    category: '빵집',
    group: '디저트',
    countInBakeryTotal: true,
  },
  {
    name: '앙버터',
    aliases: ['앙버터'],
    category: '빵집',
    group: '빵',
    countInBakeryTotal: true,
  },
  {
    name: '잠봉뵈르 샌드위치',
    aliases: ['잠봉뵈르 샌드위치', '잠봉뵈르', '잠봉뵈르샌드위치'],
    category: '음식',
    group: '샌드위치',
    countInBakeryTotal: false,
  },
  {
    name: '아보카도 샌드위치',
    aliases: ['아보카도 샌드위치', '아보카도샌드위치'],
    category: '음식',
    group: '샌드위치',
    countInBakeryTotal: false,
  },
  {
    name: '아메리카노',
    aliases: ['아메리카노', '아이스아메리카노', '아이스 아메리카노'],
    category: '음료',
    group: '커피',
    countInBakeryTotal: false,
  },
  {
    name: '라떼',
    aliases: ['라떼', '카페라떼', 'latte'],
    category: '음료',
    group: '커피',
    countInBakeryTotal: false,
  },
  {
    name: '비건라떼',
    aliases: ['비건라떼', '비건라떼', '귀리로 만든떼 라'],
    category: '음료',
    group: '커피',
    countInBakeryTotal: false,
  },
  {
    name: '마다가스카르 동료빈 라떼',
    aliases: [
      '마다가스카르빈 라떼',
      '마다가스카르바닐라빈라떼',
      '바닐라빈 라떼',
    ],
    category: '음료',
    group: '커피',
    countInBakeryTotal: false,
  },
  {
    name: '콜드브루 원액 1L',
    aliases: ['콜드브루 원액 1L', '콜드브루원액1L', '콜드브루 원액'],
    category: '음료',
    group: '콩',
    countInBakeryTotal: false,
  },
  {
    name: '커피원두 (오랑 400g)',
    aliases: ['커피원두', '커피원두 오랑 400g', '오랑 400g', '원두'],
    category: '상품',
    group: '콩',
    countInBakeryTotal: false,
  },
  {
    name: '이즈드립',
    aliases: ['이즈드립'],
    category: '음료',
    group: '커피',
    countInBakeryTotal: false,
  },
  {
    name: '구리볼',
    aliases: ['구리볼'],
    category: '알 수 없음',
    group: '알 수 없음',
    countInBakeryTotal: false,
  },
]
