export const RECEIPT_PATTERNS = [
  {
    id: '쿠팡숏',
    source: 'coupang-eats',
    detectKeywords: ['쿠팡이먹는다', '[매장용]'],
    totalPriorityLabels: ['주문 금액'],
    itemHeaderLabels: ['메뉴', '수량', '금액'],
    optionPrefixes: ['+', 'ㄴ'],
    ignoreLabels: ['거래일시', '수저포크', '주문번호', '요청사항', '친환경'],
  },
  {
    id: 'baemin-long',
    source: 'baemin',
    detectKeywords: ['알뜰 한집배달', '주문금액'],
    totalPriorityLabels: ['총결제금액', '주문금액', '합계'],
    itemHeaderLabels: ['메뉴', '수량', '금액'],
    optionPrefixes: ['+', 'ㄴ'],
    ignoreLabels: ['배달팁', '주문번호', '요청사항', '친환경'],
  },
  {
    id: '픽업 전표',
    source: '픽업',
    detectKeywords: ['픽업번호', '포장주문', '합계'],
    totalPriorityLabels: ['합계'],
    itemHeaderLabels: ['메뉴', '수량', '금액'],
    optionPrefixes: ['+', 'ㄴ'],
    ignoreLabels: ['일회용수저필요', '주문접수시간', '유형'],
  },
  {
    id: 'store-pos',
    source: 'store-pos',
    detectKeywords: ['영수증', '상호:오라운드 본점'],
    totalPriorityLabels: ['매출합계(카드)', '결제금액', '매출합계', '합계'],
    itemHeaderLabels: ['품명', '수량', '할인', '금액'],
    optionPrefixes: ['+', 'ㄴ'],
    ignoreLabels: ['순매출', '부가세', '카드번호', '카드사명', '인증번호', '계산담당자'],
  },
]
